### ISSUE TITLE
Is this client support android device

### ISSUE THREAD

**Issue by codingwatching** [maksym-pasichnyk/bedcraft#1]
Hi @maksym-pasichnyk 
Can we build bedcraft to run on android devices?
Thank you

**Comment by maksym-pasichnyk** [comment]
Hi @codingwatching, currently no, it requires some modification to renderer, now I use OpenGl 4.5 features.
I will add android support later.

**Comment by codingwatching** [comment]
Hi @maksym-pasichnyk 
Thank you so much! Keep up the good work!

**Comment by maksym-pasichnyk** [comment]
@codingwatching Thanks!
